/**
 * Product UI copy — professional English (fintech / trading terminal).
 * Canonical terms: Match · Prize Pool · Live Ranking · Stake · Demo Mode · Real Money · Top 5
 */

export const COPY = {
  brand: 'TradingDuels',
  brandTag: 'Battle Royale trading',

  nav: {
    dashboard: 'Dashboard',
    lobby: 'Lobby',
    stats: 'Stats',
    missions: 'Missions',
    leaderboard: 'Leaderboard',
    wallet: 'Wallet',
    referral: 'Invite',
    demo: 'Demo',
    signIn: 'Sign in',
    signOut: 'Sign out',
    playFree: 'Play free',
    playReal: 'Play real',
    explore: 'Browse without account',
    myProfile: 'My profile',
    arena: 'Arena',
  },

  home: {
    badge: 'Demo available',
    eyebrow: 'Global trading competition',
    title: 'Compete for the highest profit.',
    titleAccent: '10 minutes. Free to start.',
    subtitle:
      'No sign-up. No deposit. Join a live multiplayer match — up to 50 players, ranked by profit $. Top 5 share the prize pool.',
    ctaDemo: 'Play Free Demo',
    ctaDemoArrow: 'Play Free Demo →',
    ctaDemoHint: 'Virtual $5 practice match · no card required',
    howItWorksLink: 'How it works',
    howTitle: 'How it works',
    howSubtitle:
      'Three steps from free practice to a full 10-minute match.',
    howSteps: [
      {
        title: 'Join a match',
        body: 'Nickname only. Pick an asset. No email, no deposit.',
      },
      {
        title: 'Trade for 10 minutes',
        body: 'Live chart, fixed risk rules, max 2 trades — skill and timing.',
      },
      {
        title: 'Top 5 win',
        body: 'Ranked by profit $. Top 5 share the prize pool (demo shows virtual prizes).',
      },
    ],
    rulesTitle: 'Rules at a glance',
    rules: [
      {
        label: 'Lobby',
        value: 'Up to 50 players · starts from 20',
        hint: 'Demo fills with bots so you can play solo',
      },
      {
        label: 'Duration',
        value: '10:00 match clock',
        hint: 'Short format, full focus',
      },
      {
        label: 'Risk',
        value: '$10,000 virtual capital',
        hint: 'Max 2% risk · max 2 trades',
      },
      {
        label: 'Assets',
        value: 'EURUSD · NAS100 · BTCUSD · XAUUSD',
        hint: 'Ranked by profit $ — not random',
      },
    ],
    prizeSplit:
      'Top 5 split of the prize pool after the 10% platform fee',
    prizeShares: '45% · 25% · 15% · 10% · 5%',
    finalCta: 'Play Free Demo',
    finalTrust: 'Free practice · no account · no deposit',
    realEyebrow: 'Ready for real stakes later?',
    ctaSignIn: 'Sign in',
    ctaReal: 'Real money lobby',
    footerNote:
      'Demo is virtual $5 practice · Real Money available after you create an account',
  },

  demo: {
    badge: 'Demo Mode',
    nickTitle: 'Choose a nickname',
    nickHint: 'No email. No card. Just a name for the arena.',
    nickLabel: 'Nickname',
    nickPlaceholder: 'Your name in the arena',
    nickFooter: 'You’ll enter a free 10-minute practice match',
    continue: 'Continue',
    back: 'Back to home',
    changeNick: 'Change nickname',
    assetTitle: 'Choose an asset',
    assetHint: '10 min · up to 50 players · Top 5 · virtual prizes',
    assetLabels: {
      EURUSD: 'EUR / USD',
      NAS100: 'Nasdaq 100',
      BTCUSD: 'Bitcoin',
      XAUUSD: 'Gold',
    } as Record<string, string>,
    findMatch: 'Find Demo Match',
    queueTitle: 'Finding match',
    queueHint: 'Demo bots fill the lobby so you can play solo — real players appear when available.',
    queueBadge: 'Demo queue',
    players: 'players',
    waitingMin: (min: number, left: number) =>
      `Waiting for players… need ${min} (${left} more)`,
    startsIn: 'Match starts in',
    noMoney: 'No real money charged',
    demoStakeLine: 'Virtual $5 stake · prizes are simulated',
    botsHint: 'Demo bots fill seats toward 50 so solo play works',
    cancel: 'Cancel',
    wantReal: 'Want to play for real money later?',
    entering: 'Joining…',
    loading: 'Loading…',
  },

  lobby: {
    eyebrow: 'Battle Royale',
    title: 'Find a match',
    subtitle:
      'Up to 50 players · 10 minutes · ranked by profit · Top 5 share 90% of the prize pool.',
    premiumPerks:
      'Queue priority · 1 free entry/week ($1) · match chat · full stats',
    deactivatePremium: 'Disable Premium (dev)',
    activatePremium: 'Activate Premium (dev)',
    guestNote:
      'Sign in to join a queue. You can browse the leaderboard and missions without an account.',
    stake: 'Stake',
    available: 'Available',
    asset: 'Asset',
    findMatch: 'Find Match',
    joining: 'Joining…',
    useFreeEntry: 'Use free entry · $1',
    useCreditEntry: (stake: string) => `Use free $${stake} credit`,
    freeEntryOnlyStake1: 'Free entry applies only to the $1 stake',
    freeEntryAvailable: 'Free entry available ($1)',
    freeEntryAvailableHint: (week: string) =>
      `1 per week · week ${week} (UTC) · $1 stake only`,
    freeEntryUsed: 'Free entry used this week',
    freeEntryNext: (days: number) =>
      `Next in ${days} day${days === 1 ? '' : 's'} (UTC)`,
    freeCreditsTitle: 'Free entry credits',
    freeCreditsHint: (summary: string) =>
      `${summary} · real queues only · not withdrawable`,
    freeCreditForStake: (n: number, stake: string) =>
      `${n}× free $${stake} entry`,
    rules: [
      'Minimum 20 players to start the 60s countdown',
      'Maximum 50 · $10,000 virtual capital · 2 trades max',
      'Top 5 prizes · 10% platform fee',
    ],
    inQueue: 'In queue',
    prizePool: 'Prize pool',
    pot: 'Pot',
    players: 'players',
    premiumInQueue: (n: number) =>
      `${n} Premium in queue · seat priority`,
    waitingMin: (min: number) => `Waiting for minimum ${min}…`,
    waitingMinHint: (left: number) =>
      `${left} more to start the 60s countdown.`,
    matchStartsIn: 'Match starts in',
    canStillJoin: (max: number) => `Players can still join until ${max}`,
    cancelQueue: 'Leave queue',
    joinError: 'Could not join queue',
    leaveError: 'Could not leave queue',
    insufficient: (stake: number) =>
      `Insufficient balance for $${stake}. Choose another stake or deposit.`,
  },

  premium: {
    title: 'Premium — €9.99/mo',
    ctaDev: 'Activate Premium (dev)',
    benefits: [
      'Queue priority in Battle Royale',
      '1 free entry per week ($1 stake)',
      'Match chat + full stats & history',
      'PRO badge on rankings and profiles',
    ],
  },

  arena: {
    loading: 'Loading match…',
    signInToView: 'Sign in to view this match',
    signIn: 'Sign in',
    demo: 'DEMO',
    prizePool: 'Prize pool',
    pool: 'Pool',
    players: 'Players',
    stake: 'Stake',
    time: 'Time',
    end: 'END',
    myTrades: 'My trades',
    noTrades: 'No trades yet',
    openPnl: 'Open PnL',
    pendingPnl: '—',
    matchStarting: 'Match starting',
    live: 'LIVE',
    tradingSoon: 'Trading opens when the match goes live',
    liveRanking: 'Live ranking',
    yourPosition: 'Your position',
    you: 'you',
    me: 'Me',
    newOrder: 'New order',
    orderType: 'Order type',
    market: 'Market',
    limit: 'Limit',
    entryPrice: 'Entry price',
    stopLoss: 'Stop loss',
    takeProfit: 'Take profit (opt.)',
    takeProfitShort: 'TP (opt.)',
    pricePlaceholder: 'price',
    optionalPlaceholder: 'opt.',
    riskPct: (max: number) => `Risk % (max ${max}%)`,
    openMarket: (side: string) => `Open ${side} market`,
    openLimit: (side: string) => `Place ${side} limit`,
    openOrder: (side: string, type: string) => `Open ${side} ${type}`,
    riskUsed: (used: string, capital: string) =>
      `Risk used ${used}% · capital ${capital}`,
    mid: 'Mid',
    slHintLong: 'Below price',
    slHintShort: 'Above price',
    close: 'Close',
    cancel: 'Cancel',
    matchEnded: 'Match ended',
    demoEnded: 'Demo ended',
    playAgain: 'Play again',
    playReal: 'Play real money',
    anotherDemo: 'Play another demo',
    viewResult: 'View result',
    lobby: 'Lobby',
    home: 'Home',
    invalidSl: 'Invalid stop loss. Enter the exact price (e.g. 1.08450).',
    invalidTp: 'Invalid take profit. Enter a price or leave empty.',
    invalidEntry: 'Invalid entry price for limit order.',
    invalidRisk: 'Invalid risk %. Use a value between 0.01 and 2.',
    notLive: 'Match is not live — trading closed.',
    noSeat: 'You are not seated in this match.',
    maxTrades: (n: number) => `Trade limit reached (${n}/${n}).`,
    opening: 'Opening…',
    limitFilled: 'Limit filled — trade is now open',
    slHit: 'Stop loss hit',
    tpHit: 'Take profit hit',
    closedMarket: 'Trade closed',
    editLevels: 'Edit SL/TP',
    saveLevels: 'Save',
    levelsSaved: 'SL/TP updated',
    levelsSaveFailed: 'Could not update SL/TP',
    levelsDragInvalid: 'Invalid level — restored',
    slWidened: 'SL widened — extra risk reserved',
    slTightened: 'SL tightened',
    slWidenDenied: 'Not enough risk left to widen SL',
    dragLevelsHint: 'Drag SL / TP on chart',
    slRequired: 'Stop loss cannot be empty',
    riskLeft: (pct: string, usd: string) => `Risk left: ${pct}% (${usd})`,
    playersAll: (n: number) => `${n} players`,
    badgePrize: 'PRIZE',
    badgeRefund: 'STAKE BACK',
    matchEndedBanner: 'MATCH ENDED',
    forceEnd: 'End match now',
    forceEndHint: 'Demo only · skip to results',
    virtualStakeChip: 'VIRTUAL $5 MATCH',
    demoStakeLine: 'Demo stake: $5 (virtual)',
    // Live competition feedback
    zonePrize: 'PRIZE ZONE',
    zoneRefund: 'STAKE BACK',
    zoneOut: 'OUT',
    rankToastUp: (rank: number, zone: string) => `↑ #${rank} · ${zone}`,
    rankToastDown: (rank: number, zone: string) => `↓ #${rank} · ${zone}`,
    awayFromStakeBack: (gap: string) => `${gap} away from stake-back`,
    awayFromPrize: (gap: string) => `${gap} away from Top prize zone`,
    holdingStakeBack: 'Holding stake-back',
    holdingPrize: (amount: string, rank: number) =>
      `Holding prize · ${amount} · rank #${rank}`,
    holdingPrizeNoAmt: (rank: number) => `Holding prize · rank #${rank}`,
    aheadOfNext: (gap: string) => `${gap} ahead of next place`,
    finalMinute: 'FINAL MINUTE',
    finalPush: 'FINAL PUSH',
    sfxOn: 'Sound on',
    sfxOff: 'Sound off',
  },

  result: {
    won: 'YOU WON',
    topN: (n: number) => `TOP ${n}`,
    finishedRank: (n: number) => `FINISHED #${n}`,
    wonSub: (count: number) => `1st of ${count} · you dominated the field`,
    topSub: (count: number) => `Podium finish · ${count} players`,
    outSub: (count: number) =>
      `Out of ${count} players · rematch is one click away`,
    refundSub: 'Stake returned',
    position: 'Position',
    profit: 'Profit',
    prize: 'Prize',
    stakeBack: 'Stake back',
    payout: 'Payout',
    noPayout: '$0',
    zoneLabel: 'Zone',
    virtualPrize: (amount: string) => `You won ${amount} (virtual)`,
    virtualRefund: (amount: string) =>
      `${amount} stake returned (virtual)`,
    virtualStake: 'Virtual stake $5',
    gapTop5: 'Gap to Top 5',
    nearMissPrize: (rank: number, gap: string) =>
      `#${rank} · ${gap} from prize zone`,
    nearMissRefund: (rank: number, gap: string) =>
      `#${rank} · ${gap} from stake-back zone`,
    wouldHavePaid: (amount: string) =>
      `In Real Money this would have paid ~${amount}`,
    bestTrade: 'Best trade',
    trades: 'Trades',
    showDetail: 'Match details',
    hideDetail: 'Hide details',
    rank: 'Rank',
    best: 'Best',
    worst: 'Worst',
    nextStake: 'Stake for next match',
    available: 'Available',
    done: 'Done',
    insufficient: (s: string) => `Insufficient balance for ${s}`,
    canPlay: (s: string) => `You can play with a ${s} stake.`,
    depositHint: 'Deposit to compete again.',
    useStake: (s: string) => `Use ${s}`,
    deposit: 'Deposit',
    playAgain: 'PLAY AGAIN',
    playReal: 'PLAY REAL MONEY',
    anotherDemo: 'Play another demo',
    changeStake: 'Change stake',
    backLobby: 'Back to Lobby',
    closeRanking: 'Close and view final ranking',
    close: 'Close',
  },

  chat: {
    title: 'Match chat',
    readOnly: 'read-only',
    muted: 'Chat muted',
    show: 'Show',
    mute: 'Mute chat',
    empty: 'No messages yet',
    placeholder: 'Type a message…',
    premiumOnly: 'Only Premium can chat · everyone can read',
    seePremium: 'See Premium benefits →',
    premiumRequired: 'Premium required to chat',
    sendError: 'Could not send message',
  },

  auth: {
    signInTitle: 'Sign in',
    signInDesc:
      'Sign in to play, deposit, or claim rewards. Browse free without an account.',
    email: 'Email',
    emailPlaceholder: 'trader@example.com',
    password: 'Password',
    signingIn: 'Signing in…',
    noAccount: "Don't have an account?",
    register: 'Sign up',
    exploreFree: 'Keep exploring without an account',
    createTitle: 'Create account',
    createDesc:
      'Start at ELO 1000. Explore free, then sign up when you are ready to compete.',
    username: 'Username',
    displayName: 'Display name (optional)',
    usernameHint: 'letters, numbers, and _ only',
    creating: 'Creating…',
    hasAccount: 'Already have an account?',
    signInLink: 'Sign in',
    signInError: 'Could not sign in',
    registerError: 'Could not create account',
  },

  authReasons: {
    matchmaking: 'Sign in to find a match',
    challenge: 'Sign in to create or accept a challenge',
    bet: 'Sign in to place a spectator bet',
    wallet: 'Sign in to deposit or withdraw',
    mission: 'Sign in to claim rewards',
    trade: 'Sign in to trade in a match',
    dashboard: 'Sign in to view your dashboard',
  },

  wallet: {
    title: 'Wallet',
    subtitle: 'Internal USD · Min deposit $10 · Min withdrawal $20',
    signInHint:
      'Sign in to deposit or withdraw. Deposit from $10 to start competing.',
    createAccount: 'Create account',
    backLobby: 'Back to Lobby',
    needBalance: 'You need balance to play',
    needBalanceHint:
      'Deposit at least $10 (simulated) and go to the Lobby to find a match.',
    deposit50: 'Deposit $50',
    balance: 'Balance',
    available: 'Available',
    locked: 'Locked',
    moveFunds: 'Move funds',
    moveFundsHint: 'MVP: simulated deposits and withdrawals (no live gateway)',
    amount: 'Amount (USD)',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    depositOk: (s: string) => `Deposit of ${s} completed`,
    withdrawOk: (s: string) => `Withdrawal of ${s} completed`,
    ready: 'Balance ready. Next step: find a match.',
    goLobby: 'Go to Lobby',
  },

  stats: {
    loading: 'Loading stats…',
    signIn: 'Sign in to view your Battle Royale stats.',
    title: 'Stats & history',
    subtitle:
      'Free: core stats + last 10 · Premium: full history, form, asset & stake breakdowns',
    removePremium: 'Remove Premium (dev)',
    activatePremium: 'Activate Premium (dev)',
    matches: 'Matches',
    wins: 'Wins (#1)',
    top5: 'Top 5',
    prizes: 'Prizes $',
    avgProfit: 'Avg profit $',
    avgRank: 'Avg finish',
    advanced: 'Premium analytics',
    advancedDesc: (pnl: string, best: string | number, streak: number) =>
      `Total PnL ${pnl} · Best finish #${best} · Top 5 streak ${streak}`,
    assetBreakdown: 'By asset',
    stakeBreakdown: 'By stake tier',
    recentForm: 'Recent form (last 10)',
    profitFactor: 'Profit factor',
    bestFinish: 'Best finish',
    top5Streak: 'Top 5 streak',
    totalPnl: 'Total prize / PnL',
    assetLine: (games: number, top5: number, avg: string) =>
      `${games} matches · ${top5} top 5 · avg ${avg}`,
    noAssetYet: 'Play matches to unlock asset insights.',
    noStakeYet: 'Play matches to unlock stake insights.',
    noFormYet: 'Finish matches to build recent form.',
    emptyTitle: 'Play matches to unlock insights',
    emptyHint:
      'Finish Battle Royale matches to populate your stats and history.',
    goLobby: 'Go to Lobby',
    unlockTitle: 'Unlock Premium — €9.99/mo',
    unlockHint:
      'Full history, recent form, asset & stake breakdowns, Top 5 streak, queue priority, chat, free $1 entry/week.',
    history: 'History',
    lastN: (n: number) => `(last ${n} · Premium sees all)`,
    noMatches: 'No completed matches yet. Play to unlock insights.',
  },

  dashboard: {
    loading: 'Loading…',
    guestTitle: 'Your hub',
    guestHint: 'Sign in to view your balance and join Battle Royale.',
    hello: (name: string) => `Hello, ${name}`,
    newHint: 'Join a Battle Royale from the Lobby.',
    returningHint: 'Battle Royale · ranked by profit · Top 5 prizes.',
    goLobby: 'Go to Lobby',
    findMatch: 'Find Match',
    brDesc: (stakes: string, assets: string) =>
      `Stakes ${stakes} · Assets ${assets} · 10 min · max 50 players`,
  },

  leaderboard: {
    eyebrow: 'Battle Royale',
    title: 'Leaderboard',
    subtitle:
      'Ranked by ELO · BR matches, Top 5 rate, avg finish, and prize $',
    updated: (s: string) => `Updated ${s}`,
    loading: 'Loading leaderboard…',
    emptyTitle: 'No rankings yet',
    emptyHint:
      'Play Battle Royale matches to climb the board. Start in the Lobby.',
    goLobby: 'Go to Lobby',
    loadError: 'Could not load leaderboard',
    showing: (total: number, n: number) =>
      `${total} players · showing ${n}`,
    tableFrom4: ' · table from #4',
    player: 'Player',
    rank: 'Rank',
    duels: 'Matches',
    brMatches: 'BR',
    top5Pct: 'Top 5%',
    avgFinish: 'Avg fin.',
    prizeWon: 'Prize $',
  },

  profile: {
    loading: 'Loading profile…',
    notFound: 'Profile not found',
    viewLeaderboard: 'View leaderboard',
    publicProfile: 'Public profile',
    you: 'You',
    memberSince: 'Member since',
    recentHistory: 'Recent history',
    rank: 'Rank',
    position: (n: number) => `Rank #${n}`,
    noRank: 'Unranked',
    historicalAverage: 'Historical average',
    competitiveRating: 'Competitive rating',
    matches: 'Matches',
    completed: 'Completed',
    byMode: 'By mode',
    noDuels: 'No matches recorded.',
    view: 'view',
    findMatch: 'Find Match',
  },

  missions: {
    loadError: 'Could not load missions',
    loading: 'Loading missions…',
    retry: 'Retry',
    claimError: 'Could not claim reward',
    eyebrow: 'Rewards',
    title: 'Missions',
    subtitle:
      'Complete win objectives and claim rewards. Only matches meeting the minimum stake count.',
    publicCatalog: 'Public catalog',
    publicCatalogHint:
      'Browse missions and rewards. Sign in to track progress and claim.',
    signIn: 'Sign in',
    activateOnWin: 'Missions unlock when you win',
    activateHint:
      'Play matches with stake ≥ $3 (small) or ≥ $5 (monthly). Start with a match in the Lobby.',
    playNow: 'Play now',
    close: 'close',
    smallDailyCap: 'Daily reward availability',
    smallDailyCapDesc: 'Small mission claims pause when the daily limit is reached (UTC).',
    remaining: 'available today',
    active: 'Open',
    paused: 'Paused',
    paidToday: 'Claimed today',
    capReached: 'Daily limit reached. Small missions resume tomorrow (UTC).',
    missionPool: 'Monthly reward',
    poolDesc: (min: number, max: number) =>
      `Monthly mission reward $${min}–$${max} when unlocked`,
    canFundBig: 'Monthly reward available',
    insufficientFunds: 'Unlocks when available',
    rewardStatusOpen: 'Claims open',
    rewardStatusPaused: 'Temporarily paused',
    monthlyUnlockHint: 'Keep progressing — claim unlocks when available',
    smallMissions: 'Small missions · stake ≥ $3',
    bigMission: 'Big mission · stake ≥ $5 · monthly',
    updated: (s: string) => `Updated ${s} · periods in UTC`,
    progress: 'Progress',
    reward: 'Reward',
    cooldownUntil: (s: string) => `Cooldown until ${s}`,
    claiming: 'Claiming…',
    claim: (label: string) => `Claim ${label}`,
    claimed: 'Claimed',
    pausedLabel: 'Paused',
    onCooldown: 'On cooldown',
    remainingCount: (n: number) => `${n} left`,
    statusClaimable: 'Claim',
    statusClaimed: 'Done',
    statusPaused: 'Paused',
    statusCooldown: 'Cooldown',
    statusInProgress: 'In progress',
  },

  referral: {
    eyebrow: 'Invite & earn',
    title: 'Referral program',
    pitch:
      'Invite a friend. When they play 1 real match, you get a free $5 entry and they get a free $1 entry.',
    yourCode: 'Your code',
    yourLink: 'Your invite link',
    copy: 'Copy',
    copied: 'Copied',
    loading: 'Loading referral…',
    signIn: 'Sign in to get your invite link',
    statsInvited: 'Invited',
    statsPending: 'Pending',
    statsQualified: 'Qualified',
    creditsTitle: 'Free entry credits',
    creditsEmpty: 'No free entry credits yet. Invite friends to earn them.',
    creditsHint:
      'Credits are match vouchers for real queues only — not withdrawable cash. Premium weekly $1 entry is separate.',
    stakeLabel: (s: string) => `$${s} free entry`,
    expires: (s: string) => `Expires ${s}`,
    noExpiry: 'No expiry',
    statusAvailable: 'Available',
    statusUsed: 'Used',
    statusExpired: 'Expired',
    referralsTitle: 'Your invites',
    referralsEmpty: 'No one has signed up with your link yet.',
    statusPending: 'Pending',
    statusQualified: 'Qualified',
    statusRewarded: 'Rewarded',
    referredBy: (user: string) => `You joined via @${user}`,
    pendingHint: 'They need to finish 1 real BR match (any stake). Demo does not count.',
    goLobby: 'Use in Lobby',
    howTitle: 'How it works',
    howSteps: [
      'Share your link or code with a friend',
      'They create an account through your invite',
      'When they complete 1 real-money BR match ($1 / $5 / $10), both of you get free entries',
      'You: free $5 entry · Friend: free $1 entry',
    ],
    loadError: 'Could not load referral data',
    invitedBanner: (user: string) =>
      `Invited by @${user}. When you play 1 real match, you get a free $1 entry and they get a free $5 entry.`,
  },

  common: {
    loading: 'Loading…',
    error: 'Something went wrong',
    retry: 'Retry',
    close: 'Close',
  },
} as const;
